services:
  mongo:
    image: mongo:7.0.9
    container_name: mongo
    ports:
      - "27017:27017"
    networks:
      - my-network

  backend:
    build:
      context: ./java
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    networks:
      - my-network
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongo:27017/appDataBase


  frontend:
    build:
      context: ./react
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - my-network
    

networks:
  my-network:

volumes:
  mongo-data:
